// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6mnQaU-FCXOFx2JpjKmo1GPworMOGHO8',
    appId: '1:816611458402:web:c27138a719c16de338003b',
    messagingSenderId: '816611458402',
    projectId: 'activities-schedules',
    authDomain: 'activities-schedules.firebaseapp.com',
    storageBucket: 'activities-schedules.firebasestorage.app',
    measurementId: 'G-M32S0MNJM3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrjfgHF7sj5CBuxhEvnF-BPhX_f_b5P0E',
    appId: '1:816611458402:android:6632aa277eda50ab38003b',
    messagingSenderId: '816611458402',
    projectId: 'activities-schedules',
    storageBucket: 'activities-schedules.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSO22S3tofhlOxuiKusSbmYKqMWBVaq_E',
    appId: '1:816611458402:ios:5179d5de987ce67038003b',
    messagingSenderId: '816611458402',
    projectId: 'activities-schedules',
    storageBucket: 'activities-schedules.firebasestorage.app',
    iosBundleId: 'com.smartfitai.smartFitAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSO22S3tofhlOxuiKusSbmYKqMWBVaq_E',
    appId: '1:816611458402:ios:5179d5de987ce67038003b',
    messagingSenderId: '816611458402',
    projectId: 'activities-schedules',
    storageBucket: 'activities-schedules.firebasestorage.app',
    iosBundleId: 'com.smartfitai.smartFitAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6mnQaU-FCXOFx2JpjKmo1GPworMOGHO8',
    appId: '1:816611458402:web:4d782ab560a4d75e38003b',
    messagingSenderId: '816611458402',
    projectId: 'activities-schedules',
    authDomain: 'activities-schedules.firebaseapp.com',
    storageBucket: 'activities-schedules.firebasestorage.app',
    measurementId: 'G-3Z8JTL413M',
  );
}
